services:
  - type: web
    name: romantic-chatbot-backend
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install uvicorn
    startCommand: python -m uvicorn backend:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
